# Site settings
title: "Happy Counselling"
email: "HappCounselling1@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://HappyCounselling.com.au" # the base hostname & protocol for your site

twitter_username:
github_username:
analytics: 
google_verification:

# Build settings
markdown: kramdown

