# Site settings
title: "Happy Counselling"
email: "HappCounselling1@gmail.com"
description: "Person centred counselling. Online or, in person if you are in Canberra."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://HappyCounselling.com.au" # the base hostname & protocol for your site
phone: "040 0000 000"


# google analytics tracking ID
analytics: "UA-114685624-1"
google-site-verification:


# Contact form
-contact_PK: "74232faa25040a3d469d3b413eb8691c" # Enter API token here. go to https://getsimpleform.com/ and choose send me a token with email address
-# Submissions go here https://getsimpleform.com/messages?api_token=private_key
-# emails sent via http://simpleform.mailinator.com/
-# JSON messages here https://getsimpleform.com/messages.json?api_token=private_key

# Build settings
markdown: kramdown

exclude: [
    .gitignore
]
